### ISSUE TITLE
GLMPCA DR algorithm run error

### ISSUE THREAD

**Issue by xddx123** [xzhoulab/DRComparison#2]
Hi, I'am realy appreciate your work!  I have try to reproduce your work, but when run GLMPCA DR algorithm I find that there is no file call "ortho.R". And I have try to search it on Github, but find nothing, it can't be find in "https://github.com/willtownes/scrna2019" either.

**Comment by sqsun** [comment]
Thanks for letting me know this error. I have updated the call_GLMPCA.R function there. it includes the ortho functions now.  Note that this is an old version of glmpca. I strongly recommend that you use the updated version of glmpca on github https://github.com/willtownes/scrna2019.
